spring:
  application:
    name: config-server
  profiles:
    active: native


  cloud:
    config:
      server:
#        composite:
#          - type: git
#            uri: https://github.com/your-repository/config-repo
#          - type: file
#            location: classpath:/config
        git:
          uri: git@github.com:IslomW/License_Service.git
#        native:
#          search-locations: classpath:/config

server:
  port: 8071
